name: go fortune workflows

#Q1
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'

jobs:
  go-fortune:
    if: "!contains(github.event.head_commits.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        pwd
        ls -al
    - name: try checkout
      uses: actions/checkout@v3
    - name: Test
      run:
        pwd
        ls -al


#Q3
    - name: Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}

#Q4
    - name: Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_KEY }} 
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
               "type": "header",
                "text": {
                  "type": "plain_text",
                 "text": "DipSA55 CI/CD Assignment Submission",
                 "emoji": true
                }
              },
             {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Name:*\nFeng Shan"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Metriculation:*\nA0265062J"
                }
              ]
            },
            {
             "type": "section",
             "fields": [
              {
                "type": "mrkdwn",
                "text": "*Email:*\ne1045737@u.nus.edu"
              },
              {
                "type": "mrkdwn",
                "text": "*Repository:*\nhttps://github.com/ordinart/go_fortune"
              }
            ]
          },
          {
           "type": "section",
           "fields": [
            {
             "type": "mrkdwn",
             "text": "*Deployment:*\nhttps://lavish-addition-production.up.railway.app/"
            }
           ]
          },
          {
            "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://lavish-addition-production.up.railway.app/|Open Application>"
                 }
               }
             ]
           }
   

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.TEST_SUBMIT }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK




