name: go fortune workflows

# for Q1
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]'

jobs:
  go-fortune:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        pwd
        ls -al
    - name: try checkout
      uses: actions/checkout@v3
    - name: Test
      run:
        pwd
        ls -al


#Q3
    - name: Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}




